### ISSUE TITLE
Sovereign Rollup bootstrap fails

### ISSUE THREAD

**Issue by rnbguy** [informalsystems/hermes-sdk#364]
## Summary of Bug

Sometimes, at my machine, the sovereign rollup bootstrap fails. This is mainly because, the sovereign process is not given enough time to start listening to http ports and websockets.

When this happens, adding a two-seconds-sleep at following works at my machine:

https://github.com/informalsystems/hermes-sdk/blob/ed018778694d99c3a2a91c13020944198469f681/crates/sovereign/sovereign-test-components/src/bootstrap/impls/bootstrap_rollup.rs#L88-L93

## Steps to Reproduce

It is a flaky behavior.

## Acceptance Criteria

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by soareschen** [comment]
Feel free to submit a PR that wait for longer time after the rollup node is started.
